// ─────────────────────────────────────────────────────────────────────────
// MIGRATION SOURCE — copied verbatim from the public GloryTecks website
// (src/data/...). Used by seed.ts to populate MongoDB. Do not edit here;
// the canonical data now lives in the database and is managed via the CMS.
// ─────────────────────────────────────────────────────────────────────────
export type Course = {
  slug: string;
  title: string;
  category: string;
  tagline: string;
  description: string;
  duration: string;
  modules: string[];
  tools: string[];
  projects: string[];
  placement: string;
};

export const courseCategories: {
  label: string;
  items: { label: string; slug: string }[];
}[] = [
  {
    label: "Data Science",
    items: [{ label: "Data Science", slug: "data-science" }],
  },
  {
    label: "Gen AI",
    items: [{ label: "Generative AI", slug: "gen-ai" }],
  },
  {
    label: "Agentic AI",
    items: [{ label: "Agentic AI", slug: "agentic-ai" }],
  },
  {
    label: "Data Analytics",
    items: [{ label: "Data Analytics", slug: "data-analytics" }],
  },
  {
    label: "Data Engineering",
    items: [{ label: "Data Engineering", slug: "data-engineering" }],
  },
  {
    label: "MLOps",
    items: [{ label: "MLOps", slug: "mlops" }],
  },
  {
    label: "Power BI",
    items: [{ label: "Power BI", slug: "power-bi" }],
  },
  {
    label: "SQL Server",
    items: [{ label: "SQL Server", slug: "sql-server" }],
  },
  {
    label: "Python Programming",
    items: [{ label: "Python Programming", slug: "python-programming" }],
  },
];

const make = (
  slug: string,
  title: string,
  category: string,
  tagline: string,
  duration: string,
  modules: string[],
  tools: string[],
  projects: string[]
): Course => ({
  slug,
  title,
  category,
  tagline,
  description: `Master ${title} with our industry-aligned program at GloryTecks. Learn from expert mentors, work on real-time projects, and become job-ready with dedicated placement support.`,
  duration,
  modules,
  tools,
  projects,
  placement: "100% placement assistance with 500+ hiring partners. Mock interviews, resume building, and career mentorship included.",
});

export const courses: Course[] = [
  make("gen-ai", "Generative AI", "Gen AI", "Build LLM-powered apps", "5 Months",
    [
      "Generative AI Overview (Types of Models, Gen AI vs Traditional ML, Applications)",
      "Modern Generative Models (Transformers, Diffusion, GANs, VAEs)",
      "Transformers & LLMs (Architecture, Attention, Encoder/Decoder, GPT, BERT, T5)",
      "Prompt Engineering (Zero/Few-shot, Chain-of-Thought, Role-based, Optimization)",
      "Advanced LLM Concepts (Fine-Tuning vs Prompting, RAG, Embeddings, Context Windows)",
      "Vector Databases & Retrieval (FAISS, Pinecone, Chroma, Semantic Search)",
      "Gen AI Frameworks (OpenAI API, Hugging Face, LangChain, CrewAI, PhiData)",
      "Multimodal Gen AI (Stable Diffusion, DALL·E, Captioning, Audio, Vision-Language)",
      "Building Gen AI Apps (Chatbots, RAG Q&A, Content Generators, AI Assistants)",
      "Deployment & Production (FastAPI/Flask, Docker, Cloud, API Integration)",
      "Evaluation & Optimization (LLM Eval, Prompt Eval, Cost & Latency Tuning)",
      "Responsible & Safe AI (Hallucination Reduction, Bias, Privacy, Safety)",
    ],
    ["Python", "Jupyter Notebook", "Google Colab", "OpenAI API", "Hugging Face", "LangChain", "CrewAI", "PhiData", "FAISS", "Pinecone", "Chroma", "Docker", "Flask", "FastAPI", "AWS", "Azure", "GCP", "Git", "GitHub"],
    ["GPT-based AI Chatbot", "Document Q&A System (RAG)", "AI Resume & Content Generator", "Multimodal AI App", "Autonomous AI Assistant"]),
  make("agentic-ai", "Agentic AI", "Gen AI", "Build autonomous AI agents", "5 Months",
    [
      "Core AI & ML (Python, DSA, Statistics, ML & Deep Learning Fundamentals)",
      "NLP (Tokenization, Word Embeddings, Transformers, LLMs, Prompt Engineering)",
      "Agentic AI Fundamentals (Agents, Autonomous Decisions, Planning, Tool Use, Memory)",
      "Frameworks & Libraries (LangChain, LangGraph, Phidata, CrewAI, n8n)",
      "Multi-Agent Systems (Communication, Task Decomposition, Collaboration, Roles)",
      "Advanced LLM Concepts (Fine-Tuning, RAG, Vector DBs, Embeddings)",
      "Tools & Integrations (APIs, Web Scraping, MySQL Connectivity)",
      "Memory & Knowledge Systems (Short/Long-term, Knowledge Graphs, Context)",
      "Evaluation & Optimization (Prompt Optimization, Metrics, Cost, Latency)",
      "Deployment & Production (Flask, Docker, Cloud, CI/CD for AI)",
      "AI Safety & Ethics (Responsible AI, Bias, Security, Hallucination Handling)",
    ],
    ["Python", "Jupyter Notebook", "Google Colab", "OpenAI API", "Hugging Face", "LangChain", "LangGraph", "CrewAI", "PhiData", "n8n", "FAISS", "Pinecone", "Chroma", "MySQL", "Flask", "Docker", "Git", "GitHub", "AWS", "Azure", "GCP"],
    ["AI Chatbot with Tools", "Autonomous Research Agent", "AI Personal Assistant", "Multi-Agent Task Solver", "Document Q&A System (RAG)"]),
  make("mlops", "MLOps", "Gen AI", "Productionize ML systems", "4 Months",
    [
      "Introduction to MLOps (Lifecycle, MLOps vs DevOps, Production Challenges)",
      "Python for MLOps (Automation, Pipelines, APIs, Logging)",
      "ML Fundamentals (Workflow, Training, Feature Engineering, Validation)",
      "Version Control & Collaboration (Git, GitHub, Branching, Experiment Tracking)",
      "ML Pipelines & Workflow Automation (Data, Training, Orchestration)",
      "Experiment Tracking & Model Management (MLflow, Registry, Versioning)",
      "Model Deployment (Pickle/Joblib, Flask/FastAPI, Batch vs Real-time)",
      "Containerization (Docker, Images, Compose, Dockerizing ML Apps)",
      "Kubernetes for MLOps (Pods, Services, Deploying & Scaling Models)",
      "Cloud MLOps (AWS, Azure, GCP Deployment)",
      "CI/CD for ML (Automated Deployment, Testing, Continuous Training)",
      "Model Monitoring & Maintenance (Drift, Performance, Logging, Retraining)",
      "Security & Governance (Data Security, Access, Responsible AI, Compliance)",
      "Advanced MLOps (Feature Stores, Distributed Training, AutoML, Scalable Systems)",
    ],
    ["Python", "Jupyter Notebook", "Git", "GitHub", "MLflow", "Docker", "Kubernetes", "FastAPI", "Flask", "Jenkins", "Apache Airflow", "TensorFlow", "PyTorch", "AWS", "Azure", "GCP"],
    ["End-to-End ML Pipeline", "Model Registry & Versioning", "Dockerized ML API", "Kubernetes Deployment", "CI/CD ML Workflow"]),
  make("data-science", "Data Science", "Data Science & Analytics", "From data to decisions", "6 Months",
    [
      "Python for Data Science (Basics, NumPy, Pandas, Data Cleaning, Real-world Datasets)",
      "Mathematics & Statistics (Descriptive, Probability, Distributions, Hypothesis Testing, Correlation)",
      "Exploratory Data Analysis (Visualization, Pattern & Trend Analysis, Outliers, Storytelling)",
      "Data Preprocessing & Feature Engineering (Missing Values, Encoding, Scaling, PCA)",
      "Machine Learning – Supervised (Linear/Logistic Regression, Decision Trees, Random Forest, SVM)",
      "Machine Learning – Unsupervised (K-Means, Hierarchical, DBSCAN)",
      "Model Evaluation & Optimization (Cross Validation, Metrics, Hyperparameter Tuning)",
      "Deep Learning (Neural Networks, Activation, Backpropagation, CNN, RNN, LSTM)",
      "Natural Language Processing (Tokenization, TF-IDF, Word Embeddings, Sentiment Analysis)",
      "Introduction to Generative AI (Transformers, LLMs, Prompt Engineering)",
      "SQL for Data Science (Joins, Aggregations, Subqueries, Data Extraction)",
      "Data Visualization & BI (Matplotlib, Seaborn, Power BI Dashboards)",
      "Model Deployment (Pickle/Joblib, Flask, FastAPI)",
      "Career Preparation (Resume, Portfolio, LinkedIn, Mock Interviews, Case Studies)",
    ],
    ["Python", "Jupyter Notebook", "Google Colab", "NumPy", "Pandas", "Matplotlib", "Seaborn", "Scikit-learn", "TensorFlow", "PyTorch", "MySQL", "Power BI", "Flask", "FastAPI", "Git", "GitHub"],
    ["House Price Prediction", "Customer Churn Prediction", "Sales Forecasting", "Recommendation System", "NLP Sentiment Analysis"]),
  make("data-analytics", "Data Analytics", "Data Science & Analytics", "Insights that drive growth", "4 Months",
    [
      "Excel for Data Analytics (Formulas, VLOOKUP, Pivot Tables, Dashboards, Cleaning)",
      "SQL for Data Analytics (Queries, Joins, Aggregates, GROUP BY, Subqueries, Window Functions)",
      "Python for Data Analytics (NumPy, Pandas, Cleaning, CSV/Excel/JSON)",
      "Exploratory Data Analysis (Summary Stats, Distribution, Correlation, Outliers, Insights)",
      "Data Visualization (Matplotlib, Seaborn, Charts, Heatmaps, Storytelling)",
      "Power BI for BI (Power Query, Data Modeling, DAX, Dashboards, Publishing)",
      "Data Cleaning & Preparation (Missing Values, Duplicates, Feature Engineering)",
      "Business & Analytics Concepts (KPIs, Sales/Revenue, Segmentation, Forecasting, Reporting)",
      "Data Integration & Automation (Python+SQL, DB to Power BI, Report Automation)",
    ],
    ["Microsoft Excel", "MySQL", "SQL Server Management Studio", "Python", "Jupyter Notebook", "Google Colab", "NumPy", "Pandas", "Matplotlib", "Seaborn", "Microsoft Power BI", "Git", "GitHub"],
    ["Sales Analysis Dashboard", "Financial Data Analysis", "Customer Behavior Analysis", "Marketing Campaign Analytics", "Business Performance Dashboard"]),
  make("power-bi", "Power BI", "Data Science & Analytics", "Build interactive BI dashboards", "2 Months",
    [
      "Introduction to Power BI (BI Concepts, Interface, Desktop Installation)",
      "Data Import & Connectivity (Excel, CSV, SQL, APIs, Refresh)",
      "Data Transformation with Power Query (Cleaning, Missing Values, Merging)",
      "Data Modeling (Relationships, Star/Snowflake, Calculated Columns & Measures)",
      "DAX (Aggregates, Time Intelligence, Conditional, Advanced Formulas)",
      "Data Visualization (Charts, Tables, KPI Cards, Slicers, Maps, Drill-down)",
      "Dashboard Design & Storytelling (Interactive, Optimization, UI/UX)",
      "Advanced Power BI (RLS, Bookmarks, Parameters, Custom Visuals, Performance)",
      "Power BI Service & Deployment (Publishing, Sharing, Workspaces, Refresh)",
      "Power BI Integration (SQL, Excel, Python, Real-time Data)",
    ],
    ["Microsoft Power BI", "Microsoft Excel", "MySQL", "SQL Server Management Studio", "Power Query", "DAX", "Python", "Jupyter Notebook", "Google Colab", "Git", "GitHub"],
    ["Sales Dashboard", "HR Analytics Dashboard", "Financial Performance Dashboard", "Customer Insights Dashboard", "Business KPI Dashboard"]),
  make("python-programming", "Python Programming", "Programming & Databases", "Master Python end-to-end", "4 Months",
    [
      "Python Fundamentals (Variables, Data Types, Operators, I/O)",
      "Control Flow (if/elif/else, for/while, break/continue, Nested Loops)",
      "Functions (Arguments, Return, Lambda, Recursion)",
      "Data Structures (Lists, Tuples, Sets, Dicts, Comprehensions)",
      "Strings & Regex (Operations, Formatting, Pattern Matching)",
      "File Handling (Text, CSV, JSON, File Management)",
      "Exception Handling (try/except/finally, Custom Exceptions, Logging)",
      "OOP (Classes, Inheritance, Polymorphism, Encapsulation, Abstraction)",
      "Modules & Packages (Imports, Standard Libraries, Package Management)",
      "Advanced Python (Iterators, Generators, Decorators, Closures, Context Managers)",
      "Functional Programming (map, filter, reduce, Higher-order Functions)",
      "Multithreading & Multiprocessing (Threading, Parallel, Async)",
      "APIs & Web Scraping (REST, requests, BeautifulSoup)",
      "Database Connectivity (MySQL, SQLite, CRUD)",
      "Python for Data Handling (NumPy, Pandas, Visualization)",
      "Web Development (Flask, REST APIs, Backend Basics)",
      "Intro to AI & Automation (Scripts, ML Basics, AI Apps)",
      "Testing & Best Practices (Unit Testing, Optimization, Clean Code)",
    ],
    ["Python", "Visual Studio Code", "PyCharm", "Jupyter Notebook", "Google Colab", "MySQL", "Flask", "Git", "GitHub", "NumPy", "Pandas"],
    ["Student Management System", "Web Scraping Project", "REST API Application", "Automation Tool", "Data Analysis Project"]),
  make("sql-server", "SQL Server", "Programming & Databases", "Query, design & optimize databases", "2 Months",
    [
      "Introduction to SQL Server (DB Fundamentals, Install/Configure, SSMS)",
      "SQL Fundamentals (SELECT, WHERE, ORDER BY, DISTINCT, TOP, Aliases)",
      "Filtering & Conditional Queries (AND/OR/NOT, IN/BETWEEN/LIKE, NULL, CASE)",
      "Joins & Relationships (INNER, LEFT, RIGHT, FULL OUTER, SELF, Relationships)",
      "Aggregate Functions & Grouping (COUNT/SUM/AVG/MIN/MAX, GROUP BY, HAVING)",
      "Subqueries & Advanced Queries (Nested, Correlated, CTEs, UNION/INTERSECT)",
      "Window Functions (ROW_NUMBER, RANK, LEAD/LAG, PARTITION BY)",
      "Database Design (Normalization, Keys, Constraints, ER Diagrams, Schema)",
      "Stored Procedures & Functions (Procedures, UDFs, Parameters, Control Flow)",
      "Triggers & Transactions (DML Triggers, COMMIT/ROLLBACK, ACID)",
      "Performance Optimization (Query Optimization, Indexes, Execution Plans)",
      "SQL Server Security (Users, Roles, Permissions, Backup/Restore)",
      "SQL Server Integration (Python, Power BI, Import/Export, ETL)",
    ],
    ["Microsoft SQL Server", "SQL Server Management Studio", "Azure Data Studio", "Microsoft Excel", "Microsoft Power BI"],
    ["Employee Management Database", "Sales & Inventory Database", "Banking Management System", "SQL Reporting Dashboard", "Data Analysis with SQL"]),
  make("data-engineering", "Data Engineering", "Cloud & Data Engineering", "Build robust data pipelines", "3 Months",
    [
      "Python for Data Engineering (Fundamentals, File Handling, APIs, Pandas, Logging)",
      "SQL for Data Engineering (Advanced Queries, Joins, Window Functions, Stored Procedures, Optimization)",
      "Data Processing & ETL (ETL vs ELT, Extraction, Transformation, Loading, Automation)",
      "Big Data Fundamentals (Hadoop Ecosystem, Distributed Computing, Batch vs Real-time)",
      "Apache Spark (Architecture, PySpark, DataFrames, Spark SQL, Streaming, Optimization)",
      "Data Pipelines & Orchestration (Airflow, DAGs, Scheduling, Monitoring, Alerts)",
      "Data Warehousing (Concepts, Star/Snowflake Schema, OLTP vs OLAP, Modeling, Lake vs Warehouse)",
      "Microsoft Azure Data Engineering (ADF, Data Lake, Synapse, Databricks, Azure SQL)",
      "AWS Data Engineering (S3, Glue, Redshift, Lambda, EMR, Kinesis)",
      "Google Cloud Platform (BigQuery, Cloud Storage, Dataflow, Dataproc, Pub/Sub, Composer)",
      "Streaming & Real-time Data (Kafka, Stream Processing, Event-driven Architecture)",
      "Data Governance & Security (Security, IAM, Encryption, Quality, Compliance)",
      "DevOps & Deployment (Docker, CI/CD, Git, Infrastructure)",
      "Monitoring & Optimization (Pipeline Monitoring, Logging, Tuning, Cost Optimization)",
    ],
    ["Python", "Jupyter Notebook", "Google Colab", "Pandas", "MySQL", "Apache Hadoop", "Apache Spark", "PySpark", "Apache Airflow", "Apache Kafka", "Docker", "Git", "GitHub", "Microsoft Azure", "AWS", "Google Cloud", "Azure Data Factory", "Azure Databricks", "Amazon Redshift", "BigQuery"],
    ["End-to-End ETL Pipeline", "Cloud-based Data Warehouse", "Real-time Streaming Pipeline", "Data Lake Implementation", "Multi-cloud Data Engineering Project"]),
];

export const findCourse = (slug: string) => courses.find((c) => c.slug === slug);

export type SyllabusSection = { title: string; items: string[] };

export const syllabusBySlug: Record<string, SyllabusSection[]> = {
  "data-science": [
    { title: "Python for Data Science", items: ["Python Basics & Advanced Concepts", "NumPy (Numerical Computing)", "Pandas (Data Analysis & Manipulation)", "Data Cleaning & Preprocessing", "Working with Real-world Datasets"] },
    { title: "Mathematics & Statistics for Data Science", items: ["Descriptive Statistics", "Probability Concepts", "Distributions (Normal, Binomial, Poisson)", "Inferential Statistics", "Hypothesis Testing", "Correlation & Covariance"] },
    { title: "Exploratory Data Analysis (EDA)", items: ["Data Understanding & Summary", "Data Visualization (Matplotlib, Seaborn)", "Pattern & Trend Analysis", "Outlier Detection", "Feature Relationships", "Data Storytelling"] },
    { title: "Data Preprocessing & Feature Engineering", items: ["Handling Missing Values", "Encoding Categorical Variables", "Feature Scaling (Normalization, Standardization)", "Feature Selection Techniques", "Dimensionality Reduction (PCA)"] },
    { title: "Machine Learning (Core)", items: ["Supervised: Linear Regression", "Supervised: Logistic Regression", "Supervised: Decision Trees", "Supervised: Random Forest", "Supervised: Support Vector Machines (SVM)", "Unsupervised: K-Means Clustering", "Unsupervised: Hierarchical Clustering", "Unsupervised: DBSCAN"] },
    { title: "Model Evaluation & Optimization", items: ["Train/Test Split", "Cross Validation", "Evaluation Metrics (Accuracy, Precision, Recall, F1)", "Hyperparameter Tuning", "Overfitting & Underfitting"] },
    { title: "Deep Learning", items: ["Neural Networks Basics", "Activation Functions", "Forward & Backpropagation", "CNN (Computer Vision Basics)", "RNN, LSTM (Sequence Models)"] },
    { title: "Natural Language Processing (NLP)", items: ["Text Preprocessing", "Tokenization", "TF-IDF", "Word Embeddings", "Sentiment Analysis"] },
    { title: "Introduction to Generative AI", items: ["Transformers Basics", "Large Language Models (LLMs)", "Prompt Engineering Basics", "Applications of Gen AI"] },
    { title: "SQL for Data Science", items: ["SQL Basics", "Joins & Aggregations", "Subqueries", "Data Extraction & Analysis"] },
    { title: "Data Visualization & BI", items: ["Matplotlib & Seaborn", "Dashboard Concepts", "Microsoft Power BI Basics"] },
    { title: "Model Deployment", items: ["Saving Models (Pickle / Joblib)", "API Development (Flask / FastAPI)", "Model Deployment Basics"] },
    { title: "Career Preparation", items: ["Resume Building (Data Science Focus)", "Portfolio Development, LinkedIn Support", "Interview Preparation (ML + Stats + Python)", "Case Studies"] },
  ],
  "gen-ai": [
    { title: "Generative AI Overview", items: ["What is Generative AI", "Types of Generative Models", "Gen AI vs Traditional ML", "Real-world Applications"] },
    { title: "Modern Generative Models", items: ["Transformers Overview", "Diffusion Models", "GANs (Quick Recap)", "VAEs (Quick Recap)"] },
    { title: "Transformers & Large Language Models", items: ["Transformer Architecture Deep Dive", "Attention Mechanism (Self & Cross)", "Encoder vs Decoder vs Encoder-Decoder", "GPT, BERT, T5 Models", "How LLMs Work (Training & Inference)"] },
    { title: "Prompt Engineering (Core Skill)", items: ["Prompt Design Techniques", "Zero-shot, Few-shot Learning", "Chain-of-Thought Prompting", "Role-based Prompting", "Prompt Optimization"] },
    { title: "Advanced LLM Concepts", items: ["Fine-Tuning vs Prompting", "Retrieval-Augmented Generation (RAG)", "Embeddings & Similarity Search", "Context Window & Token Management"] },
    { title: "Vector Databases & Retrieval", items: ["Embeddings Generation", "Vector Databases (FAISS, Pinecone, Chroma)", "Semantic Search", "Document Indexing"] },
    { title: "Gen AI Frameworks & Tools", items: ["OpenAI API", "Hugging Face Transformers", "LangChain", "CrewAI", "PhiData"] },
    { title: "Multimodal Generative AI", items: ["Text-to-Image (Stable Diffusion, DALL·E)", "Image-to-Text (Captioning Models)", "Audio Generation", "Vision-Language Models"] },
    { title: "Building Gen AI Applications", items: ["Chatbot Development (LLM-based)", "Document Q&A Systems (RAG)", "AI Content Generators", "AI Assistants", "Workflow Automation with LLMs"] },
    { title: "Deployment & Production", items: ["FastAPI / Flask for LLM Apps", "Model Deployment Strategies", "Cloud Integration (AWS / Azure / GCP)", "Docker for AI Applications", "API Integration"] },
    { title: "Evaluation & Optimization", items: ["LLM Evaluation Techniques", "Prompt Evaluation", "Cost Optimization (Token Usage)", "Latency & Performance Tuning"] },
    { title: "Responsible & Safe AI", items: ["Hallucination Reduction Techniques", "Bias & Fairness", "Data Privacy", "Safe AI Practices"] },
  ],
  "agentic-ai": [
    { title: "Core AI & Machine Learning", items: ["Python for AI", "Data Structures & Algorithms", "Statistics & Probability", "Machine Learning Fundamentals", "Deep Learning Basics"] },
    { title: "Natural Language Processing (NLP)", items: ["Text Processing & Tokenization", "Word Embeddings (Word2Vec, GloVe)", "Transformers Architecture", "Large Language Models (LLMs)", "Prompt Engineering"] },
    { title: "Agentic AI Fundamentals", items: ["AI Agents Concepts", "Autonomous Decision Making", "Planning & Reasoning", "Tool Usage & Function Calling", "Memory in AI Agents"] },
    { title: "Frameworks & Libraries", items: ["LangChain", "LangGraph", "Phidata", "CrewAI", "n8n"] },
    { title: "Multi-Agent Systems", items: ["Agent Communication", "Task Decomposition", "Collaboration Between Agents", "Role-based Agents"] },
    { title: "Advanced LLM Concepts", items: ["Fine-Tuning LLMs", "Retrieval-Augmented Generation (RAG)", "Vector Databases", "Embeddings & Similarity Search"] },
    { title: "Tools & Integrations", items: ["APIs Integration", "Web Scraping", "Database Connectivity (MySQL)"] },
    { title: "Memory & Knowledge Systems", items: ["Short-term Memory", "Long-term Memory", "Knowledge Graphs", "Context Management"] },
    { title: "Evaluation & Optimization", items: ["Prompt Optimization", "Model Evaluation Metrics", "Cost Optimization", "Latency & Performance Tuning"] },
    { title: "Deployment & Production", items: ["Flask", "Docker & Containers", "Cloud Deployment (AWS / Azure / GCP)", "CI/CD for AI Systems"] },
    { title: "AI Safety & Ethics", items: ["Responsible AI", "Bias & Fairness", "Security in AI Agents", "Hallucination Handling"] },
  ],
  "mlops": [
    { title: "Introduction to MLOps", items: ["What is MLOps", "ML Lifecycle Overview", "MLOps vs DevOps", "Challenges in ML Production"] },
    { title: "Python for MLOps", items: ["Python for Automation", "Data Processing Pipelines", "Working with APIs", "Logging & Exception Handling"] },
    { title: "Machine Learning Fundamentals", items: ["ML Workflow Overview", "Model Training & Evaluation", "Feature Engineering Basics", "Model Validation Techniques"] },
    { title: "Version Control & Collaboration", items: ["Git Fundamentals", "GitHub Workflow", "Branching & Collaboration", "Experiment Tracking Basics"] },
    { title: "ML Pipelines & Workflow Automation", items: ["Data Pipelines", "Training Pipelines", "Workflow Automation", "Pipeline Orchestration Concepts"] },
    { title: "Experiment Tracking & Model Management", items: ["MLflow Basics", "Experiment Tracking", "Model Registry", "Model Versioning"] },
    { title: "Model Deployment", items: ["Model Serialization (Pickle, Joblib)", "REST APIs with Flask / FastAPI", "Batch vs Real-time Inference", "Deployment Strategies"] },
    { title: "Containerization & Virtualization", items: ["Docker Basics", "Docker Images & Containers", "Dockerizing ML Applications", "Docker Compose Basics"] },
    { title: "Kubernetes for MLOps", items: ["Kubernetes Fundamentals", "Pods & Services", "Deploying ML Models on Kubernetes", "Scaling ML Applications"] },
    { title: "Cloud MLOps Platforms", items: ["MLOps on AWS", "MLOps on Microsoft Azure", "MLOps on Google Cloud", "Cloud-based Model Deployment"] },
    { title: "CI/CD for Machine Learning", items: ["CI/CD Fundamentals", "Automated Model Deployment", "Testing ML Pipelines", "Continuous Training (CT)"] },
    { title: "Model Monitoring & Maintenance", items: ["Model Drift Detection", "Performance Monitoring", "Logging & Alerts", "Retraining Pipelines"] },
    { title: "Security & Governance", items: ["Data Security Basics", "Access Management", "Responsible AI Practices", "Compliance & Governance"] },
    { title: "Advanced MLOps Concepts", items: ["Feature Stores", "Distributed Training Basics", "AutoML Concepts", "Scalable ML Systems"] },
  ],
  "data-analytics": [
    { title: "Excel for Data Analytics", items: ["Excel Basics & Data Handling", "Formulas & Functions", "VLOOKUP, INDEX-MATCH, IF Functions", "Pivot Tables & Pivot Charts", "Conditional Formatting", "Data Cleaning in Excel", "Dashboard Creation"] },
    { title: "SQL for Data Analytics", items: ["Database Fundamentals", "SQL Queries (SELECT, WHERE, ORDER BY)", "Joins (INNER, LEFT, RIGHT, FULL)", "Aggregate Functions (SUM, AVG, COUNT)", "GROUP BY & HAVING", "Subqueries", "Window Functions"] },
    { title: "Python for Data Analytics", items: ["Python Basics for Analytics", "NumPy for Numerical Operations", "Pandas for Data Analysis", "Data Cleaning & Manipulation", "Working with CSV, Excel & JSON Files"] },
    { title: "Exploratory Data Analysis (EDA)", items: ["Data Understanding & Summary Statistics", "Data Distribution Analysis", "Correlation Analysis", "Outlier Detection", "Trend & Pattern Analysis", "Business Insights Generation"] },
    { title: "Data Visualization", items: ["Matplotlib", "Seaborn", "Charts & Graphs", "Heatmaps & Pairplots", "Data Storytelling Techniques"] },
    { title: "Power BI for Business Intelligence", items: ["Data Import & Transformation", "Power Query Editor", "Data Modeling", "DAX Functions", "Interactive Dashboards", "Report Publishing & Sharing"] },
    { title: "Data Cleaning & Preparation", items: ["Handling Missing Values", "Removing Duplicates", "Data Transformation", "Feature Engineering Basics"] },
    { title: "Business & Analytics Concepts", items: ["KPI Analysis", "Sales & Revenue Analysis", "Customer Segmentation", "Forecasting Basics", "Business Reporting"] },
    { title: "Data Integration & Automation", items: ["Python + SQL Integration", "Connecting Databases to Power BI", "Automating Reports & Analysis"] },
  ],
  "power-bi": [
    { title: "Introduction to Power BI", items: ["What is Business Intelligence (BI)", "Introduction to Microsoft Power BI", "Power BI Interface & Workflow", "Power BI Desktop Installation"] },
    { title: "Data Import & Connectivity", items: ["Importing Data from Excel, CSV, SQL", "Connecting Databases & APIs", "Data Source Management", "Data Refresh Techniques"] },
    { title: "Data Transformation with Power Query", items: ["Power Query Editor", "Data Cleaning Techniques", "Handling Missing Values", "Removing Duplicates", "Merging & Appending Data", "Data Transformation"] },
    { title: "Data Modeling", items: ["Relationships Between Tables", "Star Schema & Snowflake Schema", "Data Modeling Best Practices", "Calculated Columns & Measures"] },
    { title: "DAX (Data Analysis Expressions)", items: ["DAX Fundamentals", "Aggregate Functions", "Time Intelligence Functions", "Conditional Calculations", "Advanced DAX Formulas"] },
    { title: "Data Visualization", items: ["Charts & Graphs", "Tables & Matrix Visuals", "KPI Cards", "Slicers & Filters", "Maps & Geographic Visuals", "Drill-down & Drill-through Reports"] },
    { title: "Dashboard Design & Storytelling", items: ["Interactive Dashboard Creation", "Business Storytelling Techniques", "Dashboard Optimization", "UI/UX Best Practices for BI Reports"] },
    { title: "Advanced Power BI Concepts", items: ["Row-Level Security (RLS)", "Bookmarks & Buttons", "Parameters", "Custom Visuals", "Performance Optimization"] },
    { title: "Power BI Service & Deployment", items: ["Publishing Reports to Power BI Service", "Sharing Dashboards", "Workspace Management", "Scheduled Refresh", "Collaboration Features"] },
    { title: "Power BI Integration", items: ["Power BI with SQL", "Power BI with Excel", "Power BI with Python Basics", "Real-time Data Integration"] },
  ],
  "python-programming": [
    { title: "Python Fundamentals", items: ["Introduction to Python", "Variables & Data Types", "Type Casting", "Input & Output Operations", "Operators in Python"] },
    { title: "Control Flow Statements", items: ["if, elif, else Statements", "for & while Loops", "break, continue, pass", "Nested Loops"] },
    { title: "Functions in Python", items: ["Defining Functions", "Function Arguments & Parameters", "Return Statements", "Lambda Functions", "Recursion"] },
    { title: "Data Structures", items: ["Lists", "Tuples", "Sets", "Dictionaries", "List Comprehensions"] },
    { title: "Strings & Regular Expressions", items: ["String Operations & Methods", "String Formatting", "Regular Expressions (Regex)", "Pattern Matching"] },
    { title: "File Handling", items: ["Reading & Writing Files", "Working with Text Files", "CSV & JSON Handling", "File Management"] },
    { title: "Exception Handling", items: ["try, except, finally", "Custom Exceptions", "Debugging Techniques", "Logging Basics"] },
    { title: "Object-Oriented Programming (OOP)", items: ["Classes & Objects", "Constructors (__init__)", "Inheritance", "Polymorphism", "Encapsulation & Abstraction"] },
    { title: "Modules & Packages", items: ["Importing Modules", "Creating Custom Modules", "Python Standard Libraries", "Package Management"] },
    { title: "Advanced Python Concepts", items: ["Comprehensions", "Iterators & Generators", "Decorators", "Closures", "Context Managers"] },
    { title: "Functional Programming", items: ["map(), filter(), reduce()", "Lambda Expressions", "Higher-order Functions"] },
    { title: "Multithreading & Multiprocessing", items: ["Threading Basics", "Multiprocessing", "Parallel Execution", "Async Programming Basics"] },
    { title: "APIs & Web Scraping", items: ["Working with REST APIs", "API Requests using requests", "Web Scraping with BeautifulSoup", "Data Extraction Techniques"] },
    { title: "Database Connectivity", items: ["MySQL with Python", "SQLite Basics", "CRUD Operations", "Database Integration"] },
    { title: "Python for Data Handling", items: ["NumPy Basics", "Pandas DataFrames", "Data Cleaning & Analysis", "Data Visualization Basics"] },
    { title: "Web Development with Python", items: ["Flask Basics", "REST API Development", "Backend Fundamentals"] },
    { title: "Introduction to AI & Automation", items: ["Automation Scripts", "Intro to Machine Learning", "Python for AI Applications"] },
    { title: "Testing & Best Practices", items: ["Unit Testing Basics", "Code Optimization", "Debugging & Error Handling", "Writing Clean Python Code"] },
  ],
  "python-basics": [
    { title: "Python Basics", items: ["What is Python", "Features of Python", "Applications of Python", "Installing Python", "IDE Setup (VS Code / Jupyter)", "Hello World Program"] },
    { title: "Data Types & Variables", items: ["Variables: Definition & Rules", "int, float, string, bool", "Type Casting (Implicit & Explicit)"] },
    { title: "Operators", items: ["Arithmetic Operators", "Logical Operators", "Comparison Operators", "Bitwise Operators"] },
    { title: "Control Flow", items: ["If Statements", "If-Else", "Nested If", "for loop", "while loop"] },
    { title: "Functions", items: ["Function Basics", "Arguments", "Return Values", "Lambda Functions"] },
    { title: "Data Structures", items: ["Lists", "Tuples", "Sets", "Dictionaries"] },
    { title: "Strings", items: ["String Methods", "String Formatting"] },
    { title: "File Handling", items: ["Reading Files", "Writing Files"] },
    { title: "Object-Oriented Programming", items: ["Classes & Objects", "Inheritance", "Polymorphism", "Encapsulation"] },
    { title: "Advanced Python", items: ["List Comprehension", "Generators", "Decorators", "Modules & Packages"] },
    { title: "Libraries for Data Science", items: ["NumPy", "Pandas"] },
    { title: "Exception Handling", items: ["Try-Except", "Custom Exceptions"] },
  ],
  "sql-server": [
    { title: "Introduction to SQL Server", items: ["Database Fundamentals", "Introduction to Microsoft SQL Server", "Installing & Configuring SQL Server", "Introduction to SQL Server Management Studio"] },
    { title: "SQL Fundamentals", items: ["SELECT Statements", "WHERE Clause", "ORDER BY", "DISTINCT", "TOP & LIMIT Concepts", "Aliases"] },
    { title: "Filtering & Conditional Queries", items: ["AND, OR, NOT Operators", "IN, BETWEEN, LIKE", "NULL Handling", "CASE Statements"] },
    { title: "Joins & Relationships", items: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "SELF JOIN", "Table Relationships"] },
    { title: "Aggregate Functions & Grouping", items: ["COUNT(), SUM(), AVG(), MIN(), MAX()", "GROUP BY", "HAVING Clause", "Data Summarization Techniques"] },
    { title: "Subqueries & Advanced Queries", items: ["Nested Queries", "Correlated Subqueries", "Common Table Expressions (CTEs)", "Set Operators (UNION, INTERSECT)"] },
    { title: "Window Functions", items: ["ROW_NUMBER()", "RANK() & DENSE_RANK()", "LEAD() & LAG()", "PARTITION BY"] },
    { title: "Database Design", items: ["Database Normalization", "Primary & Foreign Keys", "Constraints", "ER Diagrams", "Schema Design"] },
    { title: "Stored Procedures & Functions", items: ["Creating Stored Procedures", "User-defined Functions", "Parameters & Variables", "Control Flow Statements"] },
    { title: "Triggers & Transactions", items: ["DML Triggers", "Transaction Management", "COMMIT & ROLLBACK", "ACID Properties"] },
    { title: "Performance Optimization", items: ["Query Optimization", "Indexing Techniques", "Execution Plans", "Performance Tuning Basics"] },
    { title: "SQL Server Security", items: ["User Management", "Roles & Permissions", "Backup & Restore", "Data Security Basics"] },
    { title: "SQL Server Integration", items: ["SQL with Python Basics", "SQL with Power BI", "Import/Export Data", "ETL Concepts"] },
  ],
  "data-engineering": [
    { title: "Python for Data Engineering", items: ["Python Fundamentals", "File Handling & Automation", "Working with APIs", "Data Processing with Pandas", "Logging & Error Handling"] },
    { title: "SQL for Data Engineering", items: ["Database Fundamentals", "Advanced SQL Queries", "Joins & Subqueries", "Window Functions", "Stored Procedures", "Query Optimization"] },
    { title: "Data Processing & ETL", items: ["ETL vs ELT Concepts", "Data Extraction Techniques", "Data Transformation Pipelines", "Data Loading Strategies", "Workflow Automation"] },
    { title: "Big Data Fundamentals", items: ["Introduction to Big Data", "Hadoop Ecosystem", "Distributed Computing Concepts", "Batch vs Real-time Processing"] },
    { title: "Apache Spark", items: ["Spark Architecture", "PySpark Basics", "DataFrames & RDDs", "Spark SQL", "Spark Streaming", "Performance Optimization"] },
    { title: "Data Pipelines & Orchestration", items: ["Apache Airflow", "Workflow Scheduling", "DAG Creation", "Pipeline Monitoring", "Automation & Alerts"] },
    { title: "Data Warehousing", items: ["Data Warehouse Concepts", "Star & Snowflake Schema", "OLTP vs OLAP", "Data Modeling Techniques", "Data Lake vs Data Warehouse"] },
    { title: "Microsoft Azure Data Engineering", items: ["Introduction to Microsoft Azure", "Azure Data Factory (ADF)", "Azure Data Lake Storage", "Azure Synapse Analytics", "Azure Databricks", "Azure SQL Database", "Data Pipelines in Azure"] },
    { title: "AWS Data Engineering", items: ["Introduction to AWS", "Amazon S3", "AWS Glue", "Amazon Redshift", "AWS Lambda", "Amazon EMR", "Kinesis for Streaming Data", "Data Pipelines on AWS"] },
    { title: "Google Cloud Platform (GCP)", items: ["Introduction to Google Cloud", "BigQuery", "Cloud Storage", "Dataflow", "Dataproc", "Pub/Sub Messaging", "Cloud Composer", "Data Pipelines on GCP"] },
    { title: "Streaming & Real-time Data", items: ["Apache Kafka Basics", "Stream Processing Concepts", "Real-time Data Pipelines", "Event-driven Architecture"] },
    { title: "Data Governance & Security", items: ["Data Security Fundamentals", "Access Control & IAM", "Data Encryption", "Data Quality & Validation", "Compliance Basics"] },
    { title: "DevOps & Deployment", items: ["Docker Basics", "CI/CD for Data Pipelines", "Git & GitHub", "Infrastructure Basics"] },
    { title: "Monitoring & Optimization", items: ["Pipeline Monitoring", "Logging & Debugging", "Performance Tuning", "Cost Optimization in Cloud"] },
  ],
};

